# Generated by Django 6.0.5 on 2026-05-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tag', models.CharField(choices=[('WEB', 'Web Development'), ('MOBILE', 'Mobile Development')], max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
