# Generated by Django 6.0.5 on 2026-05-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_testimonialmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestimonialModel',
            new_name='Testimonial',
        ),
    ]
