# Generated by Django 6.0.5 on 2026-05-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_rename_testimonialmodel_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_imgs/'),
        ),
    ]
