# Generated by Django 6.0.5 on 2026-05-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0004_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='decription',
            field=models.TextField(),
        ),
    ]
